#include "bgfx_window.h"
#include <windows.h>
#include <bgfx/bgfx.h>
#include <bx/math.h>
#include <cgltf.h>
#include <vector>
#include <fstream>
#pragma comment(lib,"user32.lib")
struct BVertex{float x,y,z;};static bgfx::VertexBufferHandle vb=BGFX_INVALID_HANDLE;static bgfx::IndexBufferHandle ib=BGFX_INVALID_HANDLE;static bgfx::ProgramHandle prog=BGFX_INVALID_HANDLE;static bgfx::VertexLayout layout;static bgfx::UniformHandle uMvp=BGFX_INVALID_HANDLE;static HWND gh{};
static LRESULT CALLBACK bProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_CLOSE){DestroyWindow(h);return 0;}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
static const bgfx::Memory* memFile(const char*p){std::ifstream f(p,std::ios::binary);if(!f)return nullptr;std::vector<uint8_t>b((std::istreambuf_iterator<char>(f)),{});auto*m=bgfx::alloc(uint32_t(b.size()));memcpy(m->data,b.data(),b.size());return m;}
bool BgfxWindow::Create(HINSTANCE hi,const wchar_t*cls,const wchar_t*title,int x,int y,int w,int h,const wchar_t*glb){WNDCLASSW wc{};wc.hInstance=hi;wc.lpfnWndProc=bProc;wc.lpszClassName=cls;RegisterClassW(&wc);gh=CreateWindowExW(0,cls,title,WS_OVERLAPPEDWINDOW,x,y,w,h,nullptr,nullptr,hi,nullptr);ShowWindow(gh,SW_SHOW);bgfx::Init in{};in.type=bgfx::RendererType::Count;in.platformData.nwh=gh;in.resolution.width=w;in.resolution.height=h;in.resolution.reset=BGFX_RESET_VSYNC;if(!bgfx::init(in))return false;bgfx::setViewClear(0,BGFX_CLEAR_COLOR|BGFX_CLEAR_DEPTH,0x0b1020ff,1,0);layout.begin().add(bgfx::Attrib::Position,3,bgfx::AttribType::Float).end();std::vector<BVertex>v;cgltf_options o{};cgltf_data*d=nullptr;if(cgltf_parse_file(&o,glb,&d)!=cgltf_result_success)return false;for(size_t m=0;m<d->meshes_count;m++)for(size_t p=0;p<d->meshes[m].primitives_count;p++)for(size_t a=0;a<d->meshes[m].primitives[p].attributes_count;a++)if(d->meshes[m].primitives[p].attributes[a].type==cgltf_attribute_type_position){auto*q=d->meshes[m].primitives[p].attributes[a].data;v.resize(q->count);for(size_t i=0;i<q->count;i++)cgltf_accessor_read_float(q,i,&v[i].x,3);goto done;}done:cgltf_free(d);if(v.empty())return false;vb=bgfx::createVertexBuffer(bgfx::makeRef(v.data(),uint32_t(v.size()*sizeof(BVertex))),layout);auto*vs=memFile("shaders/vs_model.bin");auto*fs=memFile("shaders/fs_model.bin");if(!vs||!fs)return false;prog=bgfx::createProgram(bgfx::createShader(vs),bgfx::createShader(fs),true);return bgfx::isValid(prog);}
void BgfxWindow::Frame(){RECT r;GetClientRect(gh,&r);bgfx::setViewRect(0,0,0,uint16_t(r.right),uint16_t(r.bottom));float eye[3]={0,0,-4},at[3]={0,0,0};float view[16],proj[16],mtx[16];bx::mtxLookAt(view,{eye[0],eye[1],eye[2]},{at[0],at[1],at[2]});bx::mtxProj(proj,60,float(r.right)/float(r.bottom),.1f,100,bgfx::getCaps()->homogeneousDepth);bx::mtxIdentity(mtx);bgfx::setViewTransform(0,view,proj);bgfx::setTransform(mtx);bgfx::setVertexBuffer(0,vb);bgfx::setState(BGFX_STATE_DEFAULT);bgfx::submit(0,prog);bgfx::frame();}
