#include "opengl_window.h"
#include <windows.h>
#include <gl/GL.h>
#include <cgltf.h>
#include <vector>
#include <string>\n#include <cstring>
#pragma comment(lib,"opengl32.lib")
using PFNGLCREATESHADERPROC=GLuint(APIENTRY*)(GLenum); using PFNGLSHADERSOURCEPROC=void(APIENTRY*)(GLuint,GLsizei,const GLchar* const*,const GLint*); using PFNGLCOMPILESHADERPROC=void(APIENTRY*)(GLuint); using PFNGLGETSHADERIVPROC=void(APIENTRY*)(GLuint,GLenum,GLint*); using PFNGLCREATEPROGRAMPROC=GLuint(APIENTRY*)(); using PFNGLATTACHSHADERPROC=void(APIENTRY*)(GLuint,GLuint); using PFNGLBINDATTRIBLOCATIONPROC=void(APIENTRY*)(GLuint,GLuint,const GLchar*); using PFNGLLINKPROGRAMPROC=void(APIENTRY*)(GLuint); using PFNGLUSEPROGRAMPROC=void(APIENTRY*)(GLuint); using PFNGLGENBUFFERSPROC=void(APIENTRY*)(GLsizei,GLuint*); using PFNGLBINDBUFFERPROC=void(APIENTRY*)(GLenum,GLuint); using PFNGLBUFFERDATAPROC=void(APIENTRY*)(GLenum,GLsizeiptr,const void*,GLenum); using PFNGLENABLEVERTEXATTRIBARRAYPROC=void(APIENTRY*)(GLuint); using PFNGLVERTEXATTRIBPOINTERPROC=void(APIENTRY*)(GLuint,GLint,GLenum,GLboolean,GLsizei,const void*); static PFNGLCREATESHADERPROC pglCreateShader; static PFNGLSHADERSOURCEPROC pglShaderSource; static PFNGLCOMPILESHADERPROC pglCompileShader; static PFNGLGETSHADERIVPROC pglGetShaderiv; static PFNGLCREATEPROGRAMPROC pglCreateProgram; static PFNGLATTACHSHADERPROC pglAttachShader; static PFNGLBINDATTRIBLOCATIONPROC pglBindAttribLocation; static PFNGLLINKPROGRAMPROC pglLinkProgram; static PFNGLUSEPROGRAMPROC pglUseProgram; static PFNGLGENBUFFERSPROC pglGenBuffers; static PFNGLBINDBUFFERPROC pglBindBuffer; static PFNGLBUFFERDATAPROC pglBufferData; static PFNGLENABLEVERTEXATTRIBARRAYPROC pglEnableVertexAttribArray; static PFNGLVERTEXATTRIBPOINTERPROC pglVertexAttribPointer; static bool loadGL(){ auto L=[](const char*n)->PROC{PROC p=wglGetProcAddress(n); if(!p||p==(PROC)1||p==(PROC)2||p==(PROC)3||p==(PROC)-1){HMODULE m=GetModuleHandleA("opengl32.dll"); p=GetProcAddress(m,n);} return p;}; pglCreateShader=(PFNGLCREATESHADERPROC)L("glCreateShader"); pglShaderSource=(PFNGLSHADERSOURCEPROC)L("glShaderSource"); pglCompileShader=(PFNGLCOMPILESHADERPROC)L("glCompileShader"); pglGetShaderiv=(PFNGLGETSHADERIVPROC)L("glGetShaderiv"); pglCreateProgram=(PFNGLCREATEPROGRAMPROC)L("glCreateProgram"); pglAttachShader=(PFNGLATTACHSHADERPROC)L("glAttachShader"); pglBindAttribLocation=(PFNGLBINDATTRIBLOCATIONPROC)L("glBindAttribLocation"); pglLinkProgram=(PFNGLLINKPROGRAMPROC)L("glLinkProgram"); pglUseProgram=(PFNGLUSEPROGRAMPROC)L("glUseProgram"); pglGenBuffers=(PFNGLGENBUFFERSPROC)L("glGenBuffers"); pglBindBuffer=(PFNGLBINDBUFFERPROC)L("glBindBuffer"); pglBufferData=(PFNGLBUFFERDATAPROC)L("glBufferData"); pglEnableVertexAttribArray=(PFNGLENABLEVERTEXATTRIBARRAYPROC)L("glEnableVertexAttribArray"); pglVertexAttribPointer=(PFNGLVERTEXATTRIBPOINTERPROC)L("glVertexAttribPointer"); return pglCreateShader&&pglShaderSource&&pglCompileShader&&pglGetShaderiv&&pglCreateProgram&&pglAttachShader&&pglBindAttribLocation&&pglLinkProgram&&pglUseProgram&&pglGenBuffers&&pglBindBuffer&&pglBufferData&&pglEnableVertexAttribArray&&pglVertexAttribPointer; }
static LRESULT CALLBACK glProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_CLOSE){DestroyWindow(h);return 0;}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
static GLuint compileGL(GLenum t,const char*s){GLuint x=pglCreateShader(t);pglShaderSource(x,1,&s,nullptr);pglCompileShader(x);GLint ok=0;pglGetShaderiv(x,GL_COMPILE_STATUS,&ok);return ok?x:0;}
static bool loadGLVerts(const wchar_t*p,std::vector<float>&v){cgltf_options o{};cgltf_data*d=nullptr;if(cgltf_parse_file(&o,p,&d)!=cgltf_result_success)return false;bool ok=false;for(size_t m=0;m<d->meshes_count&&!ok;m++)for(size_t j=0;j<d->meshes[m].primitives_count&&!ok;j++)for(size_t a=0;a<d->meshes[m].primitives[j].attributes_count;a++)if(d->meshes[m].primitives[j].attributes[a].type==cgltf_attribute_type_position){auto*q=d->meshes[m].primitives[j].attributes[a].data;v.resize(q->count*3);for(size_t i=0;i<q->count;i++)cgltf_accessor_read_float(q,i,&v[i*3],3);ok=true;break;}cgltf_free(d);return ok;}
static int glCount=0; static GLuint glProgram=0; static GLuint glBuffer=0;
bool OpenGLWindow::Create(HINSTANCE hi,const wchar_t*cls,const wchar_t*title,int x,int y,int w,int h,const wchar_t*glb){WNDCLASSW wc{};wc.hInstance=hi;wc.lpfnWndProc=glProc;wc.lpszClassName=cls;wc.style=CS_OWNDC;RegisterClassW(&wc);hwnd_=CreateWindowExW(0,cls,title,WS_OVERLAPPEDWINDOW,x,y,w,h,nullptr,nullptr,hi,nullptr);dc_=GetDC(hwnd_);PIXELFORMATDESCRIPTOR pfd{sizeof(pfd),1,PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL|PFD_DOUBLEBUFFER,PFD_TYPE_RGBA,32,0,0,0,0,0,0,0,0,0,0,0,24,8,0,PFD_MAIN_PLANE,0,0,0,0};SetPixelFormat(dc_,ChoosePixelFormat(dc_,&pfd),&pfd);rc_=wglCreateContext(dc_);wglMakeCurrent(dc_,rc_);if(!loadGL())return false;ShowWindow(hwnd_,SW_SHOW);std::vector<float>v;if(!loadGLVerts(glb,v))return false;const char*vs="#version 120\nattribute vec3 p;void main(){gl_Position=vec4(p.x*0.8,p.y*0.8,p.z*0.8-1.0,1.0);}";const char*fs="#version 120\nvoid main(){gl_FragColor=vec4(0.95,0.55,0.18,1.0);}";GLuint a=compileGL(GL_VERTEX_SHADER,vs),b=compileGL(GL_FRAGMENT_SHADER,fs);GLuint prog=pglCreateProgram();pglAttachShader(prog,a);pglAttachShader(prog,b);pglBindAttribLocation(prog,0,"p");pglLinkProgram(prog);pglUseProgram(prog);GLuint buf;pglGenBuffers(1,&buf);pglBindBuffer(GL_ARRAY_BUFFER,buf);pglBufferData(GL_ARRAY_BUFFER,v.size()*sizeof(float),v.data(),GL_STATIC_DRAW);pglEnableVertexAttribArray(0);pglVertexAttribPointer(0,3,GL_FLOAT,GL_FALSE,0,nullptr);glCount=(int)(v.size()/3);glProgram=prog;glBuffer=buf;glClearColor(.035f,.045f,.065f,1);return true;}
void OpenGLWindow::Frame(){wglMakeCurrent(dc_,rc_);RECT r;GetClientRect(hwnd_,&r);glViewport(0,0,r.right,r.bottom);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);pglUseProgram(glProgram);pglBindBuffer(GL_ARRAY_BUFFER,glBuffer);glDrawArrays(GL_TRIANGLES,0,glCount);SwapBuffers(dc_);}
OpenGLWindow::~OpenGLWindow(){if(rc_){wglMakeCurrent(nullptr,nullptr);wglDeleteContext(rc_);}if(dc_)ReleaseDC(hwnd_,dc_);}
