#include "opengl_window.h"
#include <windows.h>
#include <gl/GL.h>
#include <cgltf.h>
#include <vector>
#include <string>
#pragma comment(lib,"opengl32.lib")
static LRESULT CALLBACK glProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_CLOSE){DestroyWindow(h);return 0;}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
static GLuint compileGL(GLenum t,const char*s){GLuint x=glCreateShader(t);glShaderSource(x,1,&s,nullptr);glCompileShader(x);GLint ok=0;glGetShaderiv(x,GL_COMPILE_STATUS,&ok);return ok?x:0;}
static bool loadGLVerts(const wchar_t*p,std::vector<float>&v){cgltf_options o{};cgltf_data*d=nullptr;if(cgltf_parse_file(&o,p,&d)!=cgltf_result_success)return false;bool ok=false;for(size_t m=0;m<d->meshes_count&&!ok;m++)for(size_t j=0;j<d->meshes[m].primitives_count&&!ok;j++)for(size_t a=0;a<d->meshes[m].primitives[j].attributes_count;a++)if(d->meshes[m].primitives[j].attributes[a].type==cgltf_attribute_type_position){auto*q=d->meshes[m].primitives[j].attributes[a].data;v.resize(q->count*3);for(size_t i=0;i<q->count;i++)cgltf_accessor_read_float(q,i,&v[i*3],3);ok=true;break;}cgltf_free(d);return ok;}
bool OpenGLWindow::Create(HINSTANCE hi,const wchar_t*cls,const wchar_t*title,int x,int y,int w,int h,const wchar_t*glb){WNDCLASSW wc{};wc.hInstance=hi;wc.lpfnWndProc=glProc;wc.lpszClassName=cls;wc.style=CS_OWNDC;RegisterClassW(&wc);hwnd_=CreateWindowExW(0,cls,title,WS_OVERLAPPEDWINDOW,x,y,w,h,nullptr,nullptr,hi,nullptr);dc_=GetDC(hwnd_);PIXELFORMATDESCRIPTOR pfd{sizeof(pfd),1,PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL|PFD_DOUBLEBUFFER,PFD_TYPE_RGBA,32,0,0,0,0,0,0,0,0,0,0,0,24,8,0,PFD_MAIN_PLANE,0,0,0,0};SetPixelFormat(dc_,ChoosePixelFormat(dc_,&pfd),&pfd);rc_=wglCreateContext(dc_);wglMakeCurrent(dc_,rc_);ShowWindow(hwnd_,SW_SHOW);std::vector<float>v;if(!loadGLVerts(glb,v))return false;const char*vs="#version 120\nattribute vec3 p;void main(){gl_Position=vec4(p.x*0.8,p.y*0.8,p.z*0.8-1.0,1.0);}";const char*fs="#version 120\nvoid main(){gl_FragColor=vec4(0.95,0.55,0.18,1.0);}";GLuint a=compileGL(GL_VERTEX_SHADER,vs),b=compileGL(GL_FRAGMENT_SHADER,fs);GLuint prog=glCreateProgram();glAttachShader(prog,a);glAttachShader(prog,b);glBindAttribLocation(prog,0,"p");glLinkProgram(prog);glUseProgram(prog);GLuint buf;glGenBuffers(1,&buf);glBindBuffer(GL_ARRAY_BUFFER,buf);glBufferData(GL_ARRAY_BUFFER,v.size()*sizeof(float),v.data(),GL_STATIC_DRAW);glEnableVertexAttribArray(0);glVertexAttribPointer(0,3,GL_FLOAT,GL_FALSE,0,nullptr);glClearColor(.035f,.045f,.065f,1);return true;}
void OpenGLWindow::Frame(){wglMakeCurrent(dc_,rc_);RECT r;GetClientRect(hwnd_,&r);glViewport(0,0,r.right,r.bottom);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);glDrawArrays(GL_TRIANGLES,0,1000000);SwapBuffers(dc_);}
OpenGLWindow::~OpenGLWindow(){if(rc_){wglMakeCurrent(nullptr,nullptr);wglDeleteContext(rc_);}if(dc_)ReleaseDC(hwnd_,dc_);}
