#include "opengl_window.h"
#include <windows.h>
#include <gl/GL.h>
#include <cgltf.h>
#include <vector>
#include <string>
#include <cstddef>
using GLchar = char;
#pragma comment(lib,"opengl32.lib")
using PFNGLCREATESHADERPROC=GLuint(APIENTRY*)(GLenum);using PFNGLSHADERSOURCEPROC=void(APIENTRY*)(GLuint,GLsizei,const GLchar*const*,const GLint*);using PFNGLCOMPILESHADERPROC=void(APIENTRY*)(GLuint);using PFNGLGETSHADERIVPROC=void(APIENTRY*)(GLuint,GLenum,GLint*);using PFNGLCREATEPROGRAMPROC=GLuint(APIENTRY*)();using PFNGLATTACHSHADERPROC=void(APIENTRY*)(GLuint,GLuint);using PFNGLBINDATTRIBLOCATIONPROC=void(APIENTRY*)(GLuint,GLuint,const GLchar*);using PFNGLLINKPROGRAMPROC=void(APIENTRY*)(GLuint);using PFNGLUSEPROGRAMPROC=void(APIENTRY*)(GLuint);using PFNGLGENBUFFERSPROC=void(APIENTRY*)(GLsizei,GLuint*);using PFNGLBINDBUFFERPROC=void(APIENTRY*)(GLenum,GLuint);using PFNGLBUFFERDATAPROC=void(APIENTRY*)(GLenum,ptrdiff_t,const void*,GLenum);using PFNGLENABLEVERTEXATTRIBARRAYPROC=void(APIENTRY*)(GLuint);using PFNGLVERTEXATTRIBPOINTERPROC=void(APIENTRY*)(GLuint,GLint,GLenum,GLboolean,GLsizei,const void*);
static PFNGLCREATESHADERPROC pCreateShader;static PFNGLSHADERSOURCEPROC pShaderSource;static PFNGLCOMPILESHADERPROC pCompileShader;static PFNGLGETSHADERIVPROC pGetShaderiv;static PFNGLCREATEPROGRAMPROC pCreateProgram;static PFNGLATTACHSHADERPROC pAttachShader;static PFNGLBINDATTRIBLOCATIONPROC pBindAttribLocation;static PFNGLLINKPROGRAMPROC pLinkProgram;static PFNGLUSEPROGRAMPROC pUseProgram;static PFNGLGENBUFFERSPROC pGenBuffers;static PFNGLBINDBUFFERPROC pBindBuffer;static PFNGLBUFFERDATAPROC pBufferData;static PFNGLENABLEVERTEXATTRIBARRAYPROC pEnableVertexAttribArray;static PFNGLVERTEXATTRIBPOINTERPROC pVertexAttribPointer;
static PROC gp(const char*n){PROC p=wglGetProcAddress(n);if(!p||p==(PROC)1||p==(PROC)2||p==(PROC)3||p==(PROC)-1)p=GetProcAddress(GetModuleHandleA("opengl32.dll"),n);return p;}
static bool loadGL(){pCreateShader=(PFNGLCREATESHADERPROC)gp("glCreateShader");pShaderSource=(PFNGLSHADERSOURCEPROC)gp("glShaderSource");pCompileShader=(PFNGLCOMPILESHADERPROC)gp("glCompileShader");pGetShaderiv=(PFNGLGETSHADERIVPROC)gp("glGetShaderiv");pCreateProgram=(PFNGLCREATEPROGRAMPROC)gp("glCreateProgram");pAttachShader=(PFNGLATTACHSHADERPROC)gp("glAttachShader");pBindAttribLocation=(PFNGLBINDATTRIBLOCATIONPROC)gp("glBindAttribLocation");pLinkProgram=(PFNGLLINKPROGRAMPROC)gp("glLinkProgram");pUseProgram=(PFNGLUSEPROGRAMPROC)gp("glUseProgram");pGenBuffers=(PFNGLGENBUFFERSPROC)gp("glGenBuffers");pBindBuffer=(PFNGLBINDBUFFERPROC)gp("glBindBuffer");pBufferData=(PFNGLBUFFERDATAPROC)gp("glBufferData");pEnableVertexAttribArray=(PFNGLENABLEVERTEXATTRIBARRAYPROC)gp("glEnableVertexAttribArray");pVertexAttribPointer=(PFNGLVERTEXATTRIBPOINTERPROC)gp("glVertexAttribPointer");return pCreateShader&&pShaderSource&&pCompileShader&&pGetShaderiv&&pCreateProgram&&pAttachShader&&pBindAttribLocation&&pLinkProgram&&pUseProgram&&pGenBuffers&&pBindBuffer&&pBufferData&&pEnableVertexAttribArray&&pVertexAttribPointer;}
static LRESULT CALLBACK glProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_CLOSE){DestroyWindow(h);return 0;}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
static GLuint compileGL(GLenum t,const char*s){GLuint x=pCreateShader(t);pShaderSource(x,1,&s,nullptr);pCompileShader(x);GLint ok=0;pGetShaderiv(x,GL_COMPILE_STATUS,&ok);return ok?x:0;}
static bool loadGLVerts(const wchar_t*p,std::vector<float>&v){int n=WideCharToMultiByte(CP_UTF8,0,p,-1,nullptr,0,nullptr,nullptr);if(n<=1)return false;std::string path(n-1,'\\0');WideCharToMultiByte(CP_UTF8,0,p,-1,path.data(),n,nullptr,nullptr);cgltf_options o{};cgltf_data*d=nullptr;if(cgltf_parse_file(&o,path.c_str(),&d)!=cgltf_result_success)return false;bool ok=false;for(size_t m=0;m<d->meshes_count&&!ok;m++)for(size_t j=0;j<d->meshes[m].primitives_count&&!ok;j++)for(size_t a=0;a<d->meshes[m].primitives[j].attributes_count;a++)if(d->meshes[m].primitives[j].attributes[a].type==cgltf_attribute_type_position){auto*q=d->meshes[m].primitives[j].attributes[a].data;v.resize(q->count*3);for(size_t i=0;i<q->count;i++)cgltf_accessor_read_float(q,i,&v[i*3],3);ok=true;break;}cgltf_free(d);return ok;}
static int glCount=0;static GLuint glProgram=0;static GLuint glBuffer=0;
bool OpenGLWindow::Create(HINSTANCE hi,const wchar_t*cls,const wchar_t*title,int x,int y,int w,int h,const wchar_t*glb){WNDCLASSW wc{};wc.hInstance=hi;wc.lpfnWndProc=glProc;wc.lpszClassName=cls;wc.style=CS_OWNDC;RegisterClassW(&wc);hwnd_=CreateWindowExW(0,cls,title,WS_OVERLAPPEDWINDOW,x,y,w,h,nullptr,nullptr,hi,nullptr);dc_=GetDC(hwnd_);PIXELFORMATDESCRIPTOR pfd{sizeof(pfd),1,PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL|PFD_DOUBLEBUFFER,PFD_TYPE_RGBA,32,0,0,0,0,0,0,0,0,0,0,0,24,8,0,PFD_MAIN_PLANE,0,0,0,0};SetPixelFormat(dc_,ChoosePixelFormat(dc_,&pfd),&pfd);rc_=wglCreateContext(dc_);wglMakeCurrent(dc_,rc_);if(!loadGL())return false;ShowWindow(hwnd_,SW_SHOW);std::vector<float>v;if(!loadGLVerts(glb,v))return false;const char*vs="#version 120\nattribute vec3 p;void main(){gl_Position=vec4(p.x*.8,p.y*.8,p.z*.8-1.0,1.0);}";const char*fs="#version 120\nvoid main(){gl_FragColor=vec4(.95,.55,.18,1.0);}";GLuint a=compileGL(GL_VERTEX_SHADER,vs),b=compileGL(GL_FRAGMENT_SHADER,fs);GLuint prog=pCreateProgram();pAttachShader(prog,a);pAttachShader(prog,b);pBindAttribLocation(prog,0,"p");pLinkProgram(prog);pUseProgram(prog);GLuint buf;pGenBuffers(1,&buf);pBindBuffer(GL_ARRAY_BUFFER,buf);pBufferData(GL_ARRAY_BUFFER,v.size()*sizeof(float),v.data(),GL_STATIC_DRAW);pEnableVertexAttribArray(0);pVertexAttribPointer(0,3,GL_FLOAT,GL_FALSE,0,nullptr);glCount=(int)(v.size()/3);glProgram=prog;glBuffer=buf;glClearColor(.035f,.045f,.065f,1);return true;}
void OpenGLWindow::Frame(){wglMakeCurrent(dc_,rc_);RECT r;GetClientRect(hwnd_,&r);glViewport(0,0,r.right,r.bottom);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);pUseProgram(glProgram);pBindBuffer(GL_ARRAY_BUFFER,glBuffer);glDrawArrays(GL_TRIANGLES,0,glCount);SwapBuffers(dc_);}
OpenGLWindow::~OpenGLWindow(){if(rc_){wglMakeCurrent(nullptr,nullptr);wglDeleteContext(rc_);}if(dc_)ReleaseDC(hwnd_,dc_);}
