const $=id=>document.getElementById(id);
const messages=$("messages"), input=$("input"), send=$("send"), typing=$("typing");
let pendingImage=null, micMode="off", realtimeConnected=false, realtimeAssistant="";
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
function addMessage(role,text){if(messages.querySelector(".empty"))messages.innerHTML="";const row=document.createElement("div");row.className="msg "+role;const bubble=document.createElement("div");bubble.className="bubble";bubble.textContent=String(text||"");row.appendChild(bubble);messages.appendChild(row);messages.scrollTop=messages.scrollHeight}
function welcome(){messages.innerHTML='<div class="empty"><div class="welcome"><h1>How can I help?</h1><p>Saeed can work with your files, applications, browser and desktop tasks. Tell me what you want done.</p></div></div>'}
function setBusy(v){typing.classList.toggle("hidden",!v);send.disabled=v}
function renderMode(mode){micMode=mode||"off";document.querySelectorAll(".mode-buttons button").forEach(b=>b.classList.remove("active"));const map={always:"modeAlways",push:"modePush",off:"modeOff"};$(map[micMode])?.classList.add("active");$("micLabel").textContent=micMode==="always"?"Always Listening":micMode==="push"?"Push to Talk":"Microphone Off";const d=$("micDot");d.className="dot "+(micMode==="always"?"on":micMode==="push"?"push":"off")}
async function sendMessage(){const text=input.value.trim();if(!text&&!pendingImage)return;const image=pendingImage;pendingImage=null;input.value="";resize();addMessage("user",text||"Screen capture");setBusy(true);try{const r=await window.saeed.chat(text,image);if(r?.error)addMessage("tool",r.error);else if(r)addMessage("assistant",r)}catch(e){addMessage("tool","Error: "+e.message)}finally{setBusy(false);input.focus()}}
function resize(){input.style.height="auto";input.style.height=Math.min(120,input.scrollHeight)+"px"}
async function setMode(mode){try{realtimeMic.stop();await window.saeed.setSettings({micMode:mode,alwaysListening:mode==="always"});renderMode(mode);if(mode==="off"){await window.saeed.stopRealtime()}else{await window.saeed.startRealtime({});if(mode==="always"&&realtimeConnected)await realtimeMic.start()}}catch(e){$("connection").textContent="Microphone error: "+e.message}}
$("send").onclick=sendMessage;$("input").addEventListener("input",resize);$("input").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}});
$("newChat").onclick=async()=>{await window.saeed.clearHistory();welcome()};$("openSettings").onclick=()=>window.saeed.openSettings?.();
$("minimize").onclick=()=>window.saeed.minimizeWindow?.();$("close").onclick=()=>window.saeed.hideWindow?.();
$("capture").onclick=async()=>{try{pendingImage=await window.saeed.capture();if(pendingImage)addMessage("tool","Screen capture attached to the next message.")}catch(e){addMessage("tool","Capture failed: "+e.message)}};
$("modeAlways").onclick=()=>setMode("always");$("modePush").onclick=()=>setMode("push");$("modeOff").onclick=()=>setMode("off");
$("modePush").onmousedown=async()=>{if(micMode!=="push")return;try{if(!realtimeConnected)await window.saeed.startRealtime({});await realtimeMic.start()}catch(e){$("connection").textContent="Microphone error: "+e.message}};$("modePush").onmouseup=()=>realtimeMic.stop();$("modePush").onmouseleave=()=>realtimeMic.stop();$("modePush").ontouchstart=$("modePush").onmousedown;$("modePush").ontouchend=$("modePush").onmouseup;
class RealtimeMic{
 constructor(){this.stream=null;this.ctx=null;this.source=null;this.processor=null;this.monitor=null;this.active=false;this.playCtx=null;this.nextPlayTime=0}
 async start(){if(this.active)return;this.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});this.ctx=new AudioContext();this.source=this.ctx.createMediaStreamSource(this.stream);this.processor=this.ctx.createScriptProcessor(4096,1,1);this.processor.onaudioprocess=e=>{if(!this.active)return;const input=e.inputBuffer.getChannelData(0);let sum=0;for(let i=0;i<input.length;i++)sum+=input[i]*input[i];const rms=Math.sqrt(sum/input.length);if(rms<0.012)return;const ratio=24000/this.ctx.sampleRate,n=Math.max(1,Math.floor(input.length*ratio)),pcm=new Int16Array(n);for(let i=0;i<n;i++){const x=input[Math.min(input.length-1,Math.floor(i/ratio))];pcm[i]=Math.max(-1,Math.min(1,x))*32767}let binary="";const bytes=new Uint8Array(pcm.buffer);for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));window.saeed.sendRealtimeAudio(btoa(binary))};this.source.connect(this.processor);this.monitor=this.ctx.createGain();this.monitor.gain.value=0;this.processor.connect(this.monitor);this.monitor.connect(this.ctx.destination);this.active=true}
 stop(){this.active=false;try{this.processor?.disconnect()}catch{}try{this.monitor?.disconnect()}catch{}try{this.source?.disconnect()}catch{}try{this.stream?.getTracks().forEach(t=>t.stop())}catch{}try{this.ctx?.close()}catch{}this.processor=null;this.monitor=null;this.source=null;this.stream=null;this.ctx=null}
 playPCM(base64){try{if(!this.playCtx)this.playCtx=new AudioContext();const raw=atob(base64),pcm=new Int16Array(raw.length/2);for(let i=0;i<pcm.length;i++)pcm[i]=raw.charCodeAt(i*2)|(raw.charCodeAt(i*2+1)<<8);const buffer=this.playCtx.createBuffer(1,pcm.length,24000),ch=buffer.getChannelData(0);for(let i=0;i<pcm.length;i++)ch[i]=pcm[i]/32768;const src=this.playCtx.createBufferSource();src.buffer=buffer;src.connect(this.playCtx.destination);const now=this.playCtx.currentTime;this.nextPlayTime=Math.max(now,this.nextPlayTime);src.start(this.nextPlayTime);this.nextPlayTime+=buffer.duration}catch(e){console.warn("Realtime playback failed",e)}}
}
const realtimeMic=new RealtimeMic();
window.saeed.onEvent(e=>{if(e.type==="thinking")setBusy(true);if(e.type==="answer"){setBusy(false);addMessage("assistant",e.text||"")}if(e.type==="tool")addMessage("tool","Running: "+e.name);if(e.type==="tool_error")addMessage("tool","Failed: "+e.name+" — "+e.error)});
window.saeed.onConfirmation(async e=>{const label={write_file:"modify a file",remove_task:"delete a task",mouse_click:"click the mouse",type_text:"type text",key_press:"press a key",file_operation:"change files"}[e.name]||e.name;const ok=confirm("Saeed requests permission to "+label+".\n\n"+JSON.stringify(e.args||{},null,2)+"\n\nAllow?");await window.saeed.respondConfirmation(e.id,ok)});
window.saeed.onMicMode(renderMode);window.saeed.onShowChat(()=>window.focus());window.saeed.onHistoryCleared(welcome);
window.saeed.onRealtimeState(async(state,message)=>{realtimeConnected=state==="connected";$("connection").textContent=state==="connected"?"Listening":state==="connecting"?"Connecting…":state==="not-configured"?"API key required":"Ready";if(state!=="connected")realtimeMic.stop();else if(micMode==="always")try{await realtimeMic.start()}catch(e){$("connection").textContent="Microphone error: "+e.message}});
window.saeed.onRealtimeAudio(b=>realtimeMic.playPCM(b));window.saeed.onRealtimeAssistantDelta(t=>realtimeAssistant+=t);window.saeed.onRealtimeAssistantFinal(t=>{if(t){addMessage("assistant",t);realtimeAssistant=""}});
window.saeed.onRealtimeUserFinal(t=>{if(t)addMessage("user",t)});window.saeed.onRealtimeError(e=>{addMessage("tool","Realtime: "+e)});
(async()=>{welcome();try{const s=await window.saeed.getSettings();renderMode(s?.micMode||"off")}catch{}input.focus()})();