const {contextBridge,ipcRenderer}=require("electron");
contextBridge.exposeInMainWorld("saeed",{
 chat:(text,image=null)=>ipcRenderer.invoke("chat",{text,image}),
 capture:()=>ipcRenderer.invoke("capture"),
 getHistory:()=>ipcRenderer.invoke("history:get"),
 checkForUpdates:()=>ipcRenderer.invoke("updates:check"),installUpdate:()=>ipcRenderer.invoke("updates:install"),onUpdateProgress:f=>ipcRenderer.on("update:progress",(_,e)=>f(e)),
 getAISettings:()=>ipcRenderer.invoke("ai:get-settings"),getAIProviders:()=>ipcRenderer.invoke("ai:get-providers"),saveAISettings:settings=>ipcRenderer.invoke("ai:save-settings",settings),openAIProvider:url=>ipcRenderer.invoke("ai:open-provider",url),
 exit:()=>ipcRenderer.send("app:exit"),
 getNotifications:()=>ipcRenderer.invoke("notifications:get"),
 clearNotifications:()=>ipcRenderer.invoke("notifications:clear"),
 moveWindowBy:(dx,dy)=>ipcRenderer.send("window:move-by",dx,dy),
 showChat:()=>ipcRenderer.send("window:show-chat"),hideChat:()=>ipcRenderer.send("window:hide-chat"),
 showUpdate:()=>ipcRenderer.send("window:show-update"),closeUpdate:()=>ipcRenderer.send("window:close-update"),
 setIgnoreMouseEvents:ignore=>ipcRenderer.send("window:set-ignore-mouse-events",Boolean(ignore)),
 onEvent:f=>ipcRenderer.on("agent:event",(_,e)=>f(e)),
 onConfirmation:f=>ipcRenderer.on("agent:confirm",(_,e)=>f(e)),
 respondConfirmation:(id,approved)=>ipcRenderer.invoke("agent:confirm-response",id,approved),
 onScreenCapture:f=>ipcRenderer.on("screen:capture",(_,e)=>f(e)),
 onShowChat:f=>ipcRenderer.on("chat:show",()=>f()),onHideChat:f=>ipcRenderer.on("chat:hide",()=>f()),
 onNotification:f=>ipcRenderer.on("notification:new",(_,e)=>f(e)),
 onNotificationList:f=>ipcRenderer.on("notifications:list",(_,e)=>f(e)),
 onMute:f=>ipcRenderer.on("voice:mute",(_,e)=>f(Boolean(e))),
 onMic:f=>ipcRenderer.on("voice:mic",(_,e)=>f(Boolean(e)))
});