const $=id=>document.getElementById(id);let settings={};let active="ai";
function showTab(t){active=t;document.querySelectorAll("#tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===t));document.querySelectorAll("[data-panel]").forEach(p=>p.classList.toggle("hidden",p.dataset.panel!==t))}
document.querySelectorAll("#tabs button").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function fill(s){settings=s||{};$("provider").value=s.provider||"openai";$("model").value=s.model||"gpt-4o-mini";$("baseUrl").value=s.baseUrl||"https://api.openai.com/v1";$("sttProvider").value=s.sttProvider||"local";$("sttModel").value=s.sttModel||"whisper-1";$("realtimeModel").value=s.realtimeModel||"gpt-realtime-2.1";$("realtimeVoice").value=s.realtimeVoice||"marin";$("ttsProvider").value=s.ttsProvider||"local";$("ttsModel").value=s.ttsModel||"gpt-4o-mini-tts";$("ttsVoice").value=s.ttsVoice||"alloy";$("showSpeechText").checked=s.showSpeechText===true;$("speakResponses").checked=s.speakResponses!==false;$("language").value=s.language||"en";$("startWithWindows").value=String(s.startWithWindows!==false);$("minimizeToTray").value=String(s.minimizeToTray!==false);renderMode(s.micMode||"off");document.querySelectorAll("[data-permission]").forEach(e=>e.value=(s.permissions||{})[e.dataset.permission]||"allow")}
function renderMode(m){document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===m));settings.micMode=m}
async function save(){const p={provider:$("provider").value,model:$("model").value,baseUrl:$("baseUrl").value,sttProvider:$("sttProvider").value,sttModel:$("sttModel").value,realtimeModel:$("realtimeModel").value,realtimeVoice:$("realtimeVoice").value,ttsProvider:$("ttsProvider").value,ttsModel:$("ttsModel").value,ttsVoice:$("ttsVoice").value,showSpeechText:$("showSpeechText").checked,speakResponses:$("speakResponses").checked,language:$("language").value,startWithWindows:$("startWithWindows").value==="true",minimizeToTray:$("minimizeToTray").value==="true",micMode:settings.micMode||"off",alwaysListening:(settings.micMode||"off")==="always",permissions:{}};const key=$("key").value.trim();if(key)p.apiKey=key;const sk=$("sttKey").value.trim();if(sk)p.sttApiKey=sk;const rk=$("realtimeKey").value.trim();if(rk)p.realtimeApiKey=rk;document.querySelectorAll("[data-permission]").forEach(e=>p.permissions[e.dataset.permission]=e.value);try{await window.saeed.setSettings(p);$("status").textContent="Saved";setTimeout(()=>window.saeed.closeSettings?.(),350)}catch(e){$("status").textContent="Save failed: "+e.message}}
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>renderMode(b.dataset.mode));$("save").onclick=save;$("cancel").onclick=()=>window.saeed.closeSettings?.();$("close").onclick=()=>window.saeed.closeSettings?.();
$("provider").onchange=()=>$("baseRow").classList.toggle("hidden",$("provider").value!=="openai-compatible");
$("clearKey").onclick=async()=>{await window.saeed.setSettings({clearLlmKey:true});$("key").value="";$("status").textContent="LLM key cleared"};$("clearAll").onclick=async()=>{await window.saeed.setSettings({clearAllApiKeys:true});$("key").value="";$("sttKey").value="";$("realtimeKey").value="";$("status").textContent="API keys cleared"};
$("checkUpdates").onclick=async()=>{$("updateStatus").textContent="Checking…";try{$("updateStatus").textContent=await window.saeed.checkForUpdates()}catch(e){$("updateStatus").textContent=e.message}};
(async()=>{try{fill(await window.saeed.getSettings())}catch(e){$("status").textContent=e.message}})();